title: 'United Arab Emirates Dirham'
symbol: AED
symbol_native: د.إ.‏
decimal_digits: 2
code: AED
title_plural: 'UAE dirhams'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
