title: 'Armenian Dram'
symbol: AMD
symbol_native: դր.
decimal_digits: 0
code: AMD
title_plural: 'Armenian drams'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
