title: 'Bosnia-Herzegovina Convertible Mark'
symbol: KM
symbol_native: KM
decimal_digits: 2
code: BAM
title_plural: 'Bosnia-Herzegovina convertible marks'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
