title: 'Bahraini Dinar'
symbol: BD
symbol_native: د.ب.‏
decimal_digits: 3
code: BHD
title_plural: 'Bahraini dinars'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
