title: 'Chilean Peso'
symbol: CL$
symbol_native: $
decimal_digits: 0
code: CLP
title_plural: 'Chilean pesos'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
