title: 'Czech Republic Koruna'
symbol: Kč
symbol_native: Kč
decimal_digits: 2
code: CZK
title_plural: 'Czech Republic korunas'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
