title: 'Danish Krone'
symbol: Dkr
symbol_native: kr
decimal_digits: 2
code: DKK
title_plural: 'Danish kroner'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
