title: 'Algerian Dinar'
symbol: DA
symbol_native: د.ج.‏
decimal_digits: 2
code: DZD
title_plural: 'Algerian dinars'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
