title: 'Ethiopian Birr'
symbol: Br
symbol_native: Br
decimal_digits: 2
code: ETB
title_plural: 'Ethiopian birrs'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
