title: 'Hong Kong Dollar'
symbol: HK$
symbol_native: $
decimal_digits: 2
code: HKD
title_plural: 'Hong Kong dollars'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
