title: 'Honduran Lempira'
symbol: HNL
symbol_native: L
decimal_digits: 2
code: HNL
title_plural: 'Honduran lempiras'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
