title: 'Iraqi Dinar'
symbol: IQD
symbol_native: د.ع.‏
decimal_digits: 0
code: IQD
title_plural: 'Iraqi dinars'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
