title: 'Jordanian Dinar'
symbol: JD
symbol_native: د.أ.‏
decimal_digits: 3
code: JOD
title_plural: 'Jordanian dinars'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
