title: 'Kuwaiti Dinar'
symbol: KD
symbol_native: د.ك.‏
decimal_digits: 3
code: KWD
title_plural: 'Kuwaiti dinars'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
