title: 'Sri Lankan Rupee'
symbol: SLRs
symbol_native: SL Re
decimal_digits: 2
code: LKR
title_plural: 'Sri Lankan rupees'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
