title: 'Libyan Dinar'
symbol: LD
symbol_native: د.ل.‏
decimal_digits: 3
code: LYD
title_plural: 'Libyan dinars'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
