title: 'Moroccan Dirham'
symbol: MAD
symbol_native: د.م.‏
decimal_digits: 2
code: MAD
title_plural: 'Moroccan dirhams'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
