title: 'Myanma Kyat'
symbol: MMK
symbol_native: K
decimal_digits: 0
code: MMK
title_plural: 'Myanma kyats'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
