title: 'Pakistani Rupee'
symbol: PKRs
symbol_native: ₨
decimal_digits: 0
code: PKR
title_plural: 'Pakistani rupees'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
