title: 'Paraguayan Guarani'
symbol: ₲
symbol_native: ₲
decimal_digits: 0
code: PYG
title_plural: 'Paraguayan guaranis'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
