title: 'Serbian Dinar'
symbol: din.
symbol_native: дин.
decimal_digits: 0
code: RSD
title_plural: 'Serbian dinars'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
