title: 'Saudi Riyal'
symbol: SR
symbol_native: ر.س.‏
decimal_digits: 2
code: SAR
title_plural: 'Saudi riyals'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
