title: 'Sudanese Pound'
symbol: SDG
symbol_native: SDG
decimal_digits: 2
code: SDG
title_plural: 'Sudanese pounds'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
