title: 'Tongan Paʻanga'
symbol: T$
symbol_native: T$
decimal_digits: 2
code: TOP
title_plural: 'Tongan paʻanga'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
