title: 'Venezuelan Bolívar'
symbol: Bs.F.
symbol_native: Bs.F.
decimal_digits: 2
code: VEF
title_plural: 'Venezuelan bolívars'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
