title: 'Zimbabwean Dollar'
symbol: ZWL$
symbol_native: ZWL$
decimal_digits: 0
code: ZWL
title_plural: 'Zimbabwean Dollar'
updated_by: 346c3162-6b01-4097-b7ee-8c4482d3ec52
updated_at: 1613398632
blueprint: currencies
